name = "Slime Skies"
author = "copygirl"
version = "0.5.8"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a5e4506e6585be2cf5c3b9a582953bc17fde026ae2daca00094cb90410a1c99"

[versions]
forge = "36.2.23"
minecraft = "1.16.5"
