name = "Slime Skies"
author = "copygirl"
version = "0.5.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d54be39815a9108b4498c3ab2dc73deba8a40dc5bd4f42ddc395bab018b424e6"

[versions]
forge = "36.2.4"
minecraft = "1.16.5"
