name = "Slime Skies"
author = "copygirl"
version = "0.3.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af9ea6559c416bc65042d97cae5a891bc7bb7bd1c38907cc117129cd1f121d96"

[versions]
forge = "36.2.4"
minecraft = "1.16.5"
