name = "Slime Skies"
author = "copygirl"
version = "0.5.4"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16956bbb397d8ab4fd4d6e60ef3ad03e5573df9223a8fc99423b319a4dd8fc13"

[versions]
forge = "36.2.4"
minecraft = "1.16.5"
