name = "Slime Skies"
author = "copygirl"
version = "0.3.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c85f6a187a55015ff52b12ca57d32af900728cf75847b0fe70a7351c26bd4f8"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
