name = "Slime Skies"
author = "copygirl"
version = "0.3.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5564be5eb2297c70a3b4bc345dd606970b30401bcdbf15ad195e425cc407046a"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
