name = "Slime Skies"
author = "copygirl"
version = "0.5.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80bf4fca21c3cd7635871712de2ae89fa5f9bba848f4332db3a3009405e8fd97"

[versions]
forge = "36.2.4"
minecraft = "1.16.5"
