name = "Slime Skies"
author = "copygirl"
version = "0.4.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1dd1eb10a12320f4d3ca79e8caadb4bbbfb1241426d2c0dcbf508f2d054d2cb"

[versions]
forge = "36.2.4"
minecraft = "1.16.5"
