name = "Slime Skies"
author = "copygirl"
version = "0.4.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9723a01d34acc58b162f66f2b9a68c2b6b894533580200dac1ab260a9296e44"

[versions]
forge = "36.2.4"
minecraft = "1.16.5"
