name = "Slime Skies"
author = "copygirl"
version = "0.4.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84601f2c9f32ea511595b24552dcd866d1dd4df78997fae7f592095982eedbb1"

[versions]
forge = "36.2.4"
minecraft = "1.16.5"
