name = "Slime Skies"
author = "copygirl"
version = "0.5.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b99e052e8522649333dc8444a88a62c6befb756c594ba5f4cf719910127bfbe5"

[versions]
forge = "36.2.4"
minecraft = "1.16.5"
