name = "Slime Skies"
author = "copygirl"
version = "0.5.7"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "553e3c5b7cde99622833774cdb7558c56cbd5190435ba1dcf180cf6bf14cf85e"

[versions]
forge = "36.2.4"
minecraft = "1.16.5"
