name = "Slime Skies"
author = "copygirl"
version = "0.4.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab292762b3c17b8f68f84788d616c87c1eb99e28ab58014d3ae7b16b964c11ec"

[versions]
forge = "36.2.4"
minecraft = "1.16.5"
