name = "Slime Skies"
author = "copygirl"
version = "0.4.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5cf820c4df481853ccb2e18a1c334b17738dbfefa32250ed1b18a52e37291407"

[versions]
forge = "36.2.4"
minecraft = "1.16.5"
