name = "Slime Skies"
author = "copygirl"
version = "0.5.5"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5490828c0d80c6f012d7a19e24e9c1d488628f82964c203d07f3c7acbf16eb4"

[versions]
forge = "36.2.4"
minecraft = "1.16.5"
