name = "Slime Skies"
author = "copygirl"
version = "0.4.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce71297ee4ba120b5edd3731cba8b34c604d2fab416b2ff0bf23f4e0a0e54a44"

[versions]
forge = "36.2.4"
minecraft = "1.16.5"
