name = "Slime Skies"
author = "copygirl"
version = "0.3.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c702b2d903ceb91d785b861875a4e7f094ebc4f21a4c948d4c36950aa3de05f4"

[versions]
forge = "36.2.4"
minecraft = "1.16.5"
