name = "Slime Skies"
author = "copygirl"
version = "0.4.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d95e9b899c6767502a783616688462184c568d00a9026379f1aecccfcd46a2eb"

[versions]
forge = "36.2.4"
minecraft = "1.16.5"
