#Whether to show particles or not when crouching to grow things
showParticles = true
#whether to enable the whitelist this does not disable the blacklist
useWhiteList = false
#growables to disable crouching on
blacklist = [
  "minecraft:grass_block",
  "minecraft:netherrack", "minecraft:warped_nylium", "minecraft:crimson_nylium",
  "minecraft:grass", "minecraft:fern", "minecraft:seagrass",
  "minecraft:sunflower", "minecraft:lilac", "minecraft:rose_bush", "minecraft:peony",
  "cavesandcliffs:azalea", "cavesandcliffs:flowing_azalea", "cavesandcliffs:mss_block",
  "cavesandcliffs:big_dripleaf", "cavesandcliffs:small_dripleaf", "cavesandcliffs:rooted_dirt",
  "botanypots"
]
#growables to enable crouching on (only works if 'useWhiteList' is true and will give exclisivity to those growables)
whitelist = []
#the minimum number of crouches before the bonemeal is applied (bonemeal is applied randomly so this will not be exact)
#Range: > 0
minCrouchesToApplyBonemeal = 4
#The radius of effect in blocks of applying the growth effect. Not recommended to change due to performance.
#Range: 0 ~ 20
effectRadius = 6
#When true only saplings are allowed to grow with twerking
saplingsOnly = false
#The chance of growth effect being applied from sprinting
#Range: 0.0 ~ 1.0
sprintGrowChance = 0.0
