name = "KubeJS (Forge)"
filename = "kubejs-forge-1605.3.18-build.125.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3469/658/kubejs-forge-1605.3.18-build.125.jar"
hash-format = "murmur2"
hash = "1051973061"

[update]
[update.curseforge]
file-id = 3469658
project-id = 238086
release-channel = "beta"
