name = "Rhino"
filename = "rhino-forge-1605.1.4-build.59.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3461/548/rhino-forge-1605.1.4-build.59.jar"
hash-format = "murmur2"
hash = "3408490460"

[update]
[update.curseforge]
file-id = 3461548
project-id = 416294
release-channel = "beta"
